services:
  db:
    image: postgres:16-alpine # Image PostgreSQL légère et stable
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_PRODUCTION}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume persistant pour la base de données

  web:
    build: .
    restart: always
    entrypoint: ["/usr/bin/entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3004"]
    volumes:
      - .:/app
      - profile_images:/app/storage # Volume persistant pour Active Storage!
    ports:
      - "3004:3004"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME_PRODUCTION}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

volumes:
  postgres_data:
  profile_images: # Volume nommé pour la persistance des images